sofarsounds/maestro

packages/stories/src/atoms/atoms.stories.tsx, packages/stories/src/layout/layout.stories.tsx, packages/stories/tsconfig.json, packages/uikit/package.json, packages/uikit/src/atoms/Button/Button.test.tsx, packages/uikit/src/atoms/Button/__snapshots__/Button.test.tsx.snap, packages/uikit/src/atoms/Button/index.tsx, packages/uikit/src/atoms/Container/Container.test.tsx, packages/uikit/src/atoms/Container/__snapshots__/Container.test.tsx.snap, packages/uikit/src/atoms/Container/index.tsx, packages/uikit/src/atoms/FormElements/Base.tsx, packages/uikit/src/atoms/FormElements/FormElements.test.tsx, packages/uikit/src/atoms/FormElements/Select.tsx, packages/uikit/src/atoms/FormElements/Textarea.tsx, packages/uikit/src/atoms/FormElements/Textfield.tsx, packages/uikit/src/atoms/FormElements/__snapshots__/FormElements.test.tsx.snap, packages/uikit/src/atoms/FormElements/index.tsx, packages/uikit/src/atoms/Grid/Grid.test.tsx, packages/uikit/src/atoms/Grid/__snapshots__/Grid.test.tsx.snap, packages/uikit/src/atoms/Grid/index.tsx, packages/uikit/src/atoms/Typography/__snapshots__/Typography.test.tsx.snap, packages/uikit/src/index.tsx, packages/uikit/src/theme/index.ts, packages/uikit/src/typings/theme.ts
=> Form Elements, Layout Elements

README.md, package.json, packages/stories/.storybook/sofarTheme.js, packages/stories/package.json
Adds some docs surrounding:
- Lerna / monorepo structure
- Best practice
=> Add basic usage docs + fix storybook logo

bin/deploy-gh-pages.sh
Currently the script is using some random guy at Mozilla 😆
=> Change github pages automatic deployment author

packages/stories/src/molecules/molecules.stories.tsx, packages/uikit/package.json, packages/uikit/src/atoms/Button/__snapshots__/Button.test.tsx.snap, packages/uikit/src/atoms/Button/index.tsx, packages/uikit/src/index.tsx, packages/uikit/src/molecules/Modal/__snapshots__/index.test.tsx.snap, packages/uikit/src/molecules/Subnav/Subnav.test.tsx, packages/uikit/src/molecules/Subnav/index.tsx, yarn.lock
```js
import { Subnav } from '@sofarsounds/maestro'
<Subnav.Container>
<Subnav.Link to="/">Link 1</Subnav.Link>
<Subnav.Link active to="/">Link 2</Subnav.Link>
</Subnav.Container>
```
=> Subnav Component

packages/uikit/package.json
=> Button Sizes - Bump maestor version

packages/uikit/src/molecules/Select/__snapshots__/Input.test.tsx.snap, packages/uikit/src/molecules/Select/__snapshots__/Menu.test.tsx.snap, packages/uikit/src/molecules/Select/__snapshots__/Option.test.tsx.snap
=> Snapshot test updates

package.json
Bump project version for npm release
=> Bump project version

package.json, src/molecules/ImageWithCaption/ImageWithCaption.test.tsx, src/molecules/ImageWithCaption/index.tsx
=> Left align image with caption

package.json, src/atoms/Badge/Badge.test.tsx, src/atoms/Badge/__snapshots__/Badge.test.tsx.snap, src/atoms/Link/Link.test.tsx, src/atoms/Link/README.md, src/atoms/Link/index.ts, src/index.tsx, src/molecules/Card/CardContainer.tsx, src/molecules/Card/CardImage.tsx, src/molecules/Card/index.tsx, src/molecules/Footer/Section.tsx, src/molecules/Navbar/Item.test.tsx, src/molecules/Navbar/Item.tsx, src/molecules/Navbar/index.tsx, src/molecules/Select/Input.tsx, src/molecules/Select/__snapshots__/Input.test.tsx.snap, src/molecules/Select/index.tsx, storybook/stories/Link.stories.tsx, storybook/stories/Select.stories.tsx
- add `hasError` prop to Select
- create `Link` Component
- Add hover state to card title
- Add hover state to footer links
=> Release v1.5.6

package.json, src/molecules/Navbar/index.tsx
Fix header opening when changing viewport width
=> Fix nav width resizing bug

src/molecules/Select/Input.tsx, src/molecules/Select/index.tsx
this is a change to get the Select component to work well with the Formik library
cc/ @davidfloegel
=> allow Select to have `name`

package.json, src/atoms/Checkbox/Checkbox.test.tsx, src/atoms/Checkbox/README.md, src/atoms/Checkbox/index.tsx, src/index.tsx, storybook/stories/Checkbox.stories.tsx
**Description**
- Creation of a checkbox component
- Associated tests
**Links**
https://sofarsounds.atlassian.net/browse/TBC-220
=> Checkbox component

src/atoms/Button/Button.test.tsx, src/atoms/Button/__snapshots__/Button.test.tsx.snap, src/atoms/Button/index.tsx
Gave the inverted button a transparent background 👍
=> Make button transparent

package.json, src/molecules/HeroImage/HeroImage.test.tsx, src/molecules/HeroImage/README.md, src/molecules/HeroImage/index.tsx
Currently the hero image component takes only one image url. This PR allows this component to receive an object with image urls to be used on different screen sizes.
=> Allow hero image component to receive an array of image urls

src/atoms/Divider/Divider.test.tsx, src/atoms/Divider/README.md, src/atoms/Divider/index.tsx, storybook/stories/Divider.stories.tsx
Adds `color` prop so Divider component can take custom colors.
=> Divider color prop

src/molecules/FormGroup/FormGroup.test.tsx, src/molecules/FormGroup/__snapshots__/FormGroup.test.tsx.snap, src/molecules/FormGroup/index.tsx
When form group is in error state, color the label red as well
=> Fix FormGroup style issue

package.json, src/atoms/Button/README.md, src/atoms/Divider/Divider.test.tsx, src/atoms/Divider/README.md, src/atoms/Divider/index.tsx, src/atoms/Icon/README.md, src/atoms/Icon/index.tsx, src/atoms/Snackbar/index.tsx, src/molecules/FormGroup/__snapshots__/FormGroup.test.tsx.snap, src/molecules/Pagination/Arrow.tsx, src/molecules/Pagination/__snapshots__/Arrow.test.tsx.snap, src/molecules/Pagination/__snapshots__/Compact.test.tsx.snap, src/molecules/Pagination/__snapshots__/Ellipsis.test.tsx.snap, src/molecules/Pagination/__snapshots__/Pagination.test.tsx.snap, src/molecules/Select/__snapshots__/Input.test.tsx.snap, src/molecules/Select/__snapshots__/Select.test.tsx.snap, src/typings/theme.ts, storybook/stories/Divider.stories.tsx, storybook/stories/Header.stories.tsx, storybook/stories/Iconography.stories.tsx
update all components that expose a color prop to only allow colors defined on the theme
=> Improve typing around color prop

src/molecules/Select/Option.tsx, src/molecules/Select/README.md, src/molecules/Select/index.tsx
Add qaId props to Select and Option components.
=> Add qaId prop to Select and Option components

.gitignore, package.json, src/molecules/Select/Input.test.tsx, src/molecules/Select/Input.tsx, src/molecules/Select/README.md, storybook/stories/Select.stories.tsx
None
Ensure `data-qaid` prop is set on `<Input />` component within `<Select />` molecule.
=> Ensure data-qaid prop is set on <Input /> component within <Select /> molecule.

src/molecules/Navbar/Item.test.tsx, src/molecules/Navbar/Item.tsx, src/molecules/Navbar/README.md, storybook/stories/Navbar.stories.tsx
Add a new prop `emphasize` to a `Navbar.Item` to make it stand out.
This is required so sofar sounds can emphasize their `Join Us` menu item.
- In Storybook
- By adding another unit test
=> Emphasise nav item

.circleci/config.yml, package.json
=> bump version

.circleci/config.yml, package.json, src/atoms/Icon/index.tsx, src/atoms/Spinner/README.md, src/atoms/Spinner/index.tsx, src/index.tsx, src/molecules/Navbar/Collapsible.tsx, src/molecules/Navbar/NavbarContainer.tsx, src/molecules/Select/Input.test.tsx, src/molecules/Select/Input.tsx, src/molecules/Select/Options/index.tsx, src/molecules/Select/README.md, src/molecules/Select/Select.test.tsx, src/molecules/Select/Typeahead.test.tsx, src/molecules/Select/index.tsx, storybook/stories/Header.stories.tsx, storybook/stories/Select.stories.tsx, storybook/stories/Spinner.stories.tsx
=> Backmerge Release v7.1.0 (#239)

package.json, src/atoms/Popper/index.tsx, src/molecules/Select/Options/index.tsx, storybook/stories/Header.stories.tsx
Fixes an issue where Popper doesn't determine anchor element width correctly.
=> Fix Popper

src/atoms/Popper/calculator.ts, src/atoms/Popper/index.tsx, src/molecules/Select/Options/index.tsx, storybook/stories/Popper.stories.tsx
- Fixes more issues with our `Popper`
=> more popper fixes

package.json, src/hooks/useSelect/index.tsx, src/molecules/Select/README.md, src/molecules/Select/Typeahead.test.tsx, src/molecules/Select/index.tsx, storybook/stories/Select.stories.tsx
To be able to allow filtering by more complex rules (other than just the items label) in the Select component we have added a custom filterBy function.
- Writing new tests
=> Custom filterBy function in Select

package.json
=> Update version number to 7.2.1

package.json
=> bump version to 7.2.3

package.json
- Updates Grid to allow column start values
=> v7.3.0 release

package.json
Updating version of maestro to 7.3.2 on package.json
=> Bump version to 7.3.2

package.json
- Adds new documentation to storybook documenting font sizes
=> Bump maestro version

package.json, src/hooks/useSelect/index.tsx
Reverts sofarsounds/maestro#312
=> Revert "allow Select to be reset programatically"

package.json
- adds inverted color scheme to dropdown and menu
- Bumps Lodash
- Bumps elliptic
- Bumps acorn
- bumps websocket extensions
- bump markdown to jsx
- bump decompress
- bumps ini
=> Bump version to 7.4

package.json, src/molecules/Navbar/Navbar.test.tsx, src/molecules/Navbar/Uncollapsible.tsx, src/molecules/Navbar/index.tsx, storybook/stories/Navbar.stories.tsx
We are redesigning our navbar so that it no longer needs a hamburger
menu.  This supports backwards compatibility.
=> 🍔 Allow the disabling of a hamburger menu

package.json, src/atoms/Popper/index.tsx
=> revert change to popper z-index

package.json
Increment version, missed in last PR
=> Increment version, missed in last PR

.circleci/config.yml, package.json, webpack.config.js, yarn.lock
=> Add css-loader for StreamlineIcon

package.json, src/hooks/index.ts, src/hooks/useDeviceDetector/index.ts, src/molecules/Select/Options/index.tsx, src/molecules/Select/index.tsx, src/test/setupTests.ts
The Popper component doesn't behave as expected on mobile browsers when an input is focused and the soft keyboard is triggered (you can see this by going to www.sofarsounds.com/cities on your phone and click on the city select, you'll notice that the dropdown options are displayed in the wrong position and scrolling the page makes them reposition incorrectly). Additionally, many mobile browsers treat fixed and absolute positioned elements as static when an input is focused. Because of all this, the Popper calculations fail, displaying the select options in the wrong position.
This alternative uses a dumber component that requires less calculations and it's a bit less flexible,
in an attempt to give mobile users a better experience when using searchable select fields.
To get this done I've …
=> Implement workaround when using searchable select on mobile devices

package.json, src/molecules/Footer/LogoWithSlogan.tsx
Updates the width of the LogoWithSlogan width to better accommodate the new Logo.
Tested using the [Developing Maestro and Sofar Client Locally](https://sofarsounds.atlassian.net/wiki/spaces/ST/pages/1350565905/Developing+Maestro+and+Sofar+Client+Locally) confluence  article and verifying the logo has been updated in the Header, Footer, Checkout header. 
- [X ] My code follows the code style of this project.
=> Update LogoWithSlogan component width
