packages/stories/src/utils/utils.stories.tsx
packages/uikit/src/index.tsx
packages/uikit/src/util/index.ts
packages/uikit/src/util/withShadow.test.tsx
packages/uikit/src/util/withShadow.ts

New `withShadow` util that can be used to add shadows to other components.
```js
const IWantShadow = styled.div`
width: 100px;
height: 100px;
// if you want the developer to be able to pass in a custom shadow depth
${widthShadow};
// if you want a fixed shadow depth
${widthShadow(2)};
`
```
Shadow depth can be `1, 2, 3, 4, 5`

withShadow util

---

.circleci/config.yml
bin/deploy-gh-pages.sh

Move storybook publish to separate CI job so that it can be used on all branches. Currently publishing storybook to github pages only happens as part of the general deploy job for the master branch

CI modification: Storybook

---

packages/uikit/package.json
packages/uikit/src/hooks/useKeyDown.tsx
packages/uikit/src/hooks/useOutsideClick.tsx

Fix infinite loop whilst using `useEffect` by including `[]` at the end of the function to prevent react lifecycle

Fix useEffect lifecycle methods

---

src/molecules/Dropdown/Dropdown.test.tsx
src/molecules/Dropdown/Flyout.test.tsx
src/molecules/Dropdown/Flyout.tsx
src/molecules/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/molecules/Dropdown/index.tsx
src/molecules/Select/Input.test.tsx
src/molecules/Select/Input.tsx
src/molecules/Select/__snapshots__/Input.test.tsx.snap
storybook/stories/Dropdown.stories.tsx

- Select component didn't correctly pass-through readonly prop to input component with the correct HTML attribute
- Added the ability to hide the styling properties on the dropdown `flyout` container, so that it can become more general-purpose. Allowing you to pass the component into the dropdown without it automatically being wrapped.

Select, Dropdown Fixes

---

src/molecules/Navbar/index.tsx

Simply re-using the existing function which re-enables the body scroll

Fix body-scroll lock issue when autoclosing mobile navbar

---

src/atoms/Textarea/__snapshots__/Textarea.test.tsx.snap
src/atoms/Textfield/__snapshots__/Textfield.test.tsx.snap
src/hooks/index.ts
src/hooks/usePosition/index.ts
src/hooks/useScrollPosition/index.tsx
src/hooks/useWindowSize/index.ts
src/molecules/Dropdown/Dropdown.test.tsx
src/molecules/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/molecules/Dropdown/index.tsx
src/molecules/FormGroup/__snapshots__/FormGroup.test.tsx.snap
src/molecules/Select/__snapshots__/Input.test.tsx.snap
src/molecules/Select/__snapshots__/Menu.test.tsx.snap
src/molecules/Select/__snapshots__/Select.test.tsx.snap
src/util/StickyContainerV2/calculator.test.ts
src/util/StickyContainerV2/calculator.ts
src/util/StickyContainerV2/index.tsx
src/util/index.ts
storybook/stories/Dropdown.stories.tsx
storybook/stories/Header.stories.tsx
storybook/stories/StickyContainer.stories.tsx

A new sticky container that has more configuration options and can adjust to window size by automatically flipping direction and moving according to how much window space there is.
New Sticky Container can be used like this
```js
<StickyContainerV2
anchorEl={ref}
anchorOrigin={{
vertical: 'top',
horizontal: 'left'
}}
transformOrigin={{
vertical: 'bottom',
horizontal: 'right'
}}
>
Sticky Content
</StickyContainerV2>
```
Inspiration for anchorOrigin and transformOrigin taken from material ui.
**Things left to do** 
- Responsiveness / auto flip side if not enough space etc
- Offset prop (talk to Dan, is it actually needed?)
- Documentation
- Test coverage

New Sticky Container

---

package.json
src/molecules/Navbar/NavbarContainer.test.tsx
src/molecules/Navbar/NavbarContainer.tsx
src/molecules/Navbar/README.md
src/molecules/Navbar/index.tsx
storybook/stories/Navbar.stories.tsx

Add two new props to make the Navbar component a bit more flexible:
- absolutePosition: sets `position: absolute`
- transparent: sets `background: transparent` when window width is >= 768px
[JIRA](https://sofarsounds.atlassian.net/browse/THEOC-339) - This is part of the work needed to create the transparent navigation we have on the /about/hosts page.

Add absolute and transparent props to Navbar component

---

src/atoms/Button/__snapshots__/Button.test.tsx.snap
src/atoms/Button/index.tsx
storybook/stories/Button.stories.tsx

The outline button is now transparent but the focus property was set to some sort of green color 👎 so I've changed the focus property to transparent and edited the storybook.
Before:
After:

Change focus property on transparent button

---

src/atoms/Responsive/index.tsx

The `Responsive` component uses `window` to grab the device window size and adds event listeners to it. On the server, `window` is not defined, so trying to render a page using the `Responsive` component throws a `ReferenceError: window is not defined` error. To avoid this we need to check if `window` is defined before accessing its width, adding event listeners.

Fix Responsive component undefined window bug

---

package.json
src/molecules/Select/Input.test.tsx
src/molecules/Select/Input.tsx
src/molecules/Select/Select.test.tsx
src/molecules/Select/__snapshots__/Input.test.tsx.snap
src/molecules/Select/__snapshots__/Select.test.tsx.snap

While testing a form with a Select component, we found that when clicking the
toggle for the Select component it was triggering the form submission (as
opposed to clicking the "Submit" button. This was due to the fact that no type
attribute was specified on the button element that triggers the dropdown of
select inputs. This commit adds this type attribute to fix this. It also adds
some additional data-qaids to enable easier testing of Select Inputs.

Add type=button to input button to prevent triggering of form submission when toggling the select dropdown

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
src/atoms/Grid/__snapshots__/Grid.test.tsx.snap
src/atoms/Grid/index.tsx

Currently when using the `<Grid>` component the developer has the option to define the breakpoints
for the different columns.
```
<Col xs={12} sm={6} md={4} lg={2}>Content...</Col>
```
However, the mapping for the props to the corresponding media queries was wrong. This PR fixes that
- Tested locally on storybook
- Updated unit tests / snapshot tests

Fix <Col> media query mapping

---

.circleci/config.yml
Procfile
app.json
package.json
yarn.lock

This PR enables heroku review apps and removes the github pages deployment process for storybook.
To be able to review, test and design review new components and fixes on maestro we currently used github pages to deploy a static version of the storybook for every PR.
However, the process is a bit flawed in that it would only work for the _first_ commit on a branch. After that, there was an issue with accessing the updated version.
In addition to that, the size of the maestro repo had grown to almost half a gigabyte.

Heroku Review apps

---

package.json
src/molecules/Footer/Top.tsx
src/molecules/Footer/index.tsx
storybook/stories/Footer.stories.tsx

We want to add priority city links to our Sofar navigation footer so that we’re surfacing these cities to google more frequently.
The footer on sofar-main has been updated in https://github.com/sofarsounds/sofar-main/pull/5792 and we want to make sure its consistent across all pages, so we need to update it on fan-exp and artist-mico repos.
- [ ??? ] My code follows the code style of this project.

Add City Links to Footer Component

---

src/atoms/MenuHeader/index.tsx
src/hooks/useSelect/index.tsx
src/molecules/Select/Options/index.tsx
src/molecules/Select/Typeahead.test.tsx
src/molecules/Select/index.tsx
storybook/stories/Select.stories.tsx

Adds two new props to the `Select` to allow the display of an initial set of popular picks.
```
<Select
popularOptions: [top5cities],
getPopularOptionsTitle: (options) => `Top ${options.length} Cities:`
/>
```
This enables us to display the `Top 10 Cities` on the sofar sounds cities select.
- Locally on storybook
- With new tests

4: Popular Options Select

---

.circleci/config.yml

Change the circle config to re-use the shared executor

add shared-setup-exec back in

---

src/atoms/Icon/index.tsx
src/atoms/Spinner/README.md
src/atoms/Spinner/index.tsx
src/index.tsx
src/molecules/Select/Input.test.tsx
src/molecules/Select/Input.tsx
src/molecules/Select/Options/index.tsx
src/molecules/Select/README.md
src/molecules/Select/Select.test.tsx
src/molecules/Select/Typeahead.test.tsx
src/molecules/Select/index.tsx
storybook/stories/Select.stories.tsx
storybook/stories/Spinner.stories.tsx

The `Select` component needs to be able to handle a `loading` and `error` state to indicate to the user what's happening. This is especially important for Selects which fetch data from an api.
- Add `state` prop which can be set to `ready`, `loading` or `error` (defaults to `ready`)
- Add `Spinner` atom component
- Display `Spinner` when loading
- Display error icon when error occurred
- Update `Select` Readme
- Locally in storybook
- By writing new tests

add an error & loading state to the Select

---

src/molecules/Navbar/Collapsible.tsx
src/molecules/Navbar/NavbarContainer.tsx
storybook/stories/Header.stories.tsx

The `<Navbar />` has a left and right section. Currently, when opening the navigation on mobile devices, the left section will be rendered at the bottom. We have made the decision to flip that around and render it at the top.
- In storybook

Re-order Navbar items in mobile view

---

package.json
src/atoms/Popper/index.tsx

Fixes an issue where the Popper component horizontal transform origin didn't work correctly
if no width was passed in manually.
- In storybook

Fix issue with Popper when no width is set

---

src/atoms/Grid/Grid.test.tsx
src/atoms/Grid/README.md
src/atoms/Grid/__snapshots__/Grid.test.tsx.snap
src/atoms/Grid/index.tsx
storybook/stories/Grid.stories.tsx

Adds props to allow us to define where in the grid a column starts
Rather than using auto so that all cols flow after each other we can
pass in additional props to define the starting point on that row.
These props set grid-column-start if not defined it is backwards
compatible and sets it as auto.
We have designs where not all columns follow in the next available
column. With the current grid we can not achieve that using this component
Unit test (via snapshot) and storybook testing

Allow Cols to start at defined points in the grid

---

package.json
src/atoms/Responsive/README.md
src/atoms/Responsive/index.tsx
storybook/stories/Responsive.stories.tsx

This adds a `showOnSizes` parameter to the `<Responsive>` atom, so that we can accomplish more complex responsive behavior needed for the Artist DB (for the dividers between rows of artist cards) than is currently possible with the `<Responsive>` atom, since it only has `showUp`, `hideUp`, `show`, and `hide` parameters. The `showOnSizes` param will let you simply have an element show on medium and XL screens but not large screens, for example.
View the new storybook test that was added to the Responsive section of storybook.

allow showOnSizes array param on Responsive wrapper

---

storybook/stories/Typography.stories.tsx

Adds a new story which displays typographical componets font size.
To allow easier lookup of current font size for typographical components
provide a table of components and size across responsive layouts.  These
are taken from our theme so should get updated in realtime

Add size guide storybook for easy lookup

---

package.json
src/atoms/Button/index.tsx
src/molecules/Select/Input.tsx
src/molecules/Select/index.tsx

1. Added focusability to wrapped div of the Select component
2. updated focus state on inverted color theme for button and select
Since we've had to build the "select" component using a div (instead of a select html element) for the functionality we need, it's not currently keyboard accessible. This change makes the select component visibly focasable on tab. 
Only visually tested in storybook. Let me know if this should have a test written for it. 
- [] New feature (non-breaking change which adds functionality)

Fix focusability issues on Select component

---

package.json
src/atoms/Button/__snapshots__/Button.test.tsx.snap
src/atoms/Button/index.tsx

Updated the disabled state of tertiary/inverted button: overrode background color it was inheriting from the primary button on disabled so it kept the black background and only the text and border changes to blue smoke. 
[JIRA ticket](https://sofarsounds.atlassian.net/browse/THEOC-1638)
Tested locally with storybook, Design approval requested (but presumably non-blocking for a small fix like this)

Updated disabled state of tertiary/inverted button

---

package.json
src/atoms/Button/__snapshots__/Button.test.tsx.snap
src/atoms/Button/index.tsx

Test this by running `yarn start` to open the storybook, then check the Button story, go to the Outline button, and check the disabled state to true. (see screenshot)

fix Outline button disabled state

---

package.json
src/hooks/useSelect/index.tsx
src/molecules/Select/README.md
src/molecules/Select/Select.test.tsx
src/molecules/Select/index.tsx
storybook/stories/Select.stories.tsx

Currently the Select component only takes a default value prop, but it's not possible to programmatically update a select value from outside the component. This change adds a value prop that allows us to pass a selected option.
This change is needed in order to allow some more complex form interactions that require programmatically selecting an option in a Select component after some other event happens in a form.
Added an example to Storybook. And a unit test.

Allow Select component to take a value prop

---

package.json
src/hooks/useSelect/index.tsx
storybook/stories/Select.stories.tsx

Allows the Select to be reset through the `value` prop. Simplified version that has been tested end-2-end. Adds a knob to the Typeahead storybook tests so that maestro testers can more easily preview the reset function. 
Sometimes in a dynamic form we want to reset a Select, for example if some other data has changed. Currently there was a way to programmatically set the value but this effect didn't allow `null|undefined` values.
Tested with [https://github.com/sofarsounds/sofar-client/pull/877](https://github.com/sofarsounds/sofar-client/pull/877) and [https://github.com/sofarsounds/sofar-main/pull/6801](https://github.com/sofarsounds/sofar-main/pull/6801) using yarn link. (react, react-dom and styled-components also need to be yarn linked, see below:)
```
cd ~/maestro
yarn install
yarn …
```

allow Select to be reset programmatically

---

src/atoms/Menu/index.tsx
src/atoms/MenuHeader/index.tsx
src/atoms/MenuItem/index.tsx
src/molecules/Dropdown/index.tsx
src/theme/global.ts
storybook/stories/Dropdown.stories.tsx
storybook/stories/Menu.stories.tsx

For the new navigation bar on sofar client we need to have the ability
to invert the colors to a dark theme ffor the dropdown and navigation.
As part of this it was needed to edit the global theme so color is not
applied specifically to all fields to allow inheritence from the parent.
This has been moved to the body selector so it should still get applied
to all elements through inheritence
via storybook, no unit tests added as this is all style, and no substance

Allow us to invert colors on dropdown & menu

---

package.json
src/theme/global.ts

A previous update to ensure we can override link colors and inherit from
the parent container meant that unless defined it reverted to browser
defaults.  This sets the link color within the global theme whilst still
allowing overrides

Specify default link colors

---

webpack.config.js

Integrated `webpack-build-analyzer` on maestro which now can be run using `yarn build` to get an idea of what constitutes the Maestro production bundle.
- There was some confusion and blindspot trying to understand what constituted the maestro production build which led to integrating this.
- Go to maestro.
- Run `yarn build`.
- You should see a new browser window popup with these bundle view.

Ability to have a Visual of the Maestro Buildpack

---

package.json
src/molecules/IconLabel/IconLabel.test.tsx
src/molecules/IconLabel/index.tsx
storybook/stories/IconLabel.stories.tsx

Extend IconLabel component to:
- Allow the component to be styled using styled components
- Prevent label text from getting truncated if not needed
- Allow the component to render a colored circle without an icon when needed
- Allow the component to take an upper label text prop that is displayed above the main label
We need these changes to implement the styles required for the Team section on the Events Details modal. Screenshot of the mocks:
You can test this by going to storybook and checking that all implementations of the IconLabel component look good. Play around with new implementations.

Extend IconLabel functionalities

---

package.json
src/atoms/Popper/index.tsx

This PR adds a zIndex prop to the Popper component, which defaults to 500. This shouldn't change any functionality but will allow components that use Popper to override the zIndex of 500 which was being hard coded before. 
We would like to customize the sofar-client InfoBox component zIndex so that it will render underneath the navbar.
The Popper should work as expected in storybook, with no change in functionality or visual appearance.

add zIndex as Popper prop

---

package.json
src/atoms/StreamlineIcon/StreamlineIcon.css
src/atoms/StreamlineIcon/index.tsx
src/index.tsx

The original plan was to self-host the streamline-react-wrapper repo and install it via the github URL, but it was having trouble resolving the package, and the wrapper is just a simple React component mapping some props to CSS classes with no dependencies, so I think it makes sense to just copy the component into our `atoms` for now. It will be used the same way on the sofar-client side so no other client changes should need to be made.

copy streamline-react-wrapper component into atoms

---

package.json
src/molecules/IconLabel/index.tsx
storybook/stories/IconLabel.stories.tsx

Set the width in components where we use IconLabel and set the default to 100%. Updated IconLabel story.
related sofar-client PR: https://github.com/sofarsounds/sofar-client/pull/1546
Width of the IconLabel now adjusts to container so it doesn't leave weird gaps or alignment issues where it's used.
Pull down this branch on sofar-client and link it to this local version of Maestro ([Directions on how to do that can be found here](https://sofarsounds.atlassian.net/wiki/spaces/ST/pages/1350565905/Developing+Maestro+and+Sofar+Client+Locally)). 
Test concert planner at phone and tablet widths using Chrome device emulator (or probably just adjusting the width of the window):
- Event Planner Card: Artists and Venue 
- Event Planner Expand Details Modal: Team tab

IconLabel: Removed fixed width from default of component
